spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: btsy-intw
      auto-offset-reset: earliest
    producer:
      retries: 0
    template:
      default-topic: jackpot-bets
      dlq-topic: jackpot-bets-dlq
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
application:
  contribution:
    linear:
      minimum-contribution: 0.001
      maximum-contribution: 0.5
    fixed:
      contribution: 0.2
  win-chance:
    linear:
      minimum-win-chance: 0.00001
    fixed:
      chance: 0.0001